## no)5

In [1]:
import numpy as np

In [2]:
Matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])

In [3]:
print(Matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
Transpose = np.array(Matrix.T)

In [5]:
print(Transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [6]:
Determinant = np.linalg.det(Matrix)

In [7]:
print(Determinant)

0.2299999999999999


In [8]:
Matrix = np.linalg.eig(Matrix)

In [9]:
print(Matrix)

EigResult(eigenvalues=array([2.04100779, 0.82188052, 0.13711169]), eigenvectors=array([[-0.43721717, -0.85359707, -0.28321933],
       [-0.59931898,  0.51133314, -0.61591816],
       [-0.67056536,  0.09955128,  0.73514055]]))


## no)6

In [9]:
import numpy as np

In [ ]:
Poisson_distribution 